sudo: false

language: ruby

rvm:
  - "1.9.3"

cache: bundler

before_install:
  - gem update bundler # Ensure we use the latest version of bundler. Travis' default version of outdated.

  # Run Elasticsearch as a daemon
  - curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.13.zip
  - unzip elasticsearch-0.90.13.zip
  - elasticsearch-0.90.13/bin/elasticsearch

  # Run MongoDB as a daemon
  - curl -O https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-2.6.11.tgz
  - tar -zxf mongodb-linux-x86_64-2.6.11.tgz
  - export PATH=mongodb-linux-x86_64-2.6.11/bin:$PATH
  - mkdir -p ./mongo/db
  - mkdir -p ./mongo/log
  - mongod --fork --dbpath ./mongo/db --logpath ./mongo/log/mongodb.log

script: bundle exec rspec
